on:
  schedule:
    - cron:  '15 3 * * 6'
    
  workflow_dispatch:

name: generate-translations

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_KEY }}
      WEBLATE_KEY: ${{ secrets.WEBLATE_KEY }}
      QML_REPO: jaspmachinelearning-qml
      R_REPO: jaspmachinelearning-r

    steps:
      - uses: jasp-stats/jasp-actions/wlcLock@master

      - uses: jasp-stats/jasp-actions/translations@master
